repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: debug-statements
          - id: detect-private-key
          - id: check-added-large-files
          - id: check-builtin-literals
          - id: name-tests-test
    - repo: local
      hooks:
          - id: black
            name: black
            entry: black
            language: system
            exclude: ^migrations/
            types: [python]
          - id: flake8
            name: flake8
            entry: flake8 --max-line-length=88 --enable-extensions=nqa
            language: system
            types: [python]
          - id: isort
            name: isort
            entry: isort --profile=black
            language: system
            types: [python]
