# Generated by Django 5.1.2 on 2024-11-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(max_length=50, unique=True)),
                ('dev_join_eui', models.CharField(max_length=50, unique=True)),
                ('dev_name', models.CharField(max_length=100)),
                ('dev_owner', models.CharField(max_length=100)),
                ('dev_owner_email', models.EmailField(max_length=254)),
                ('dev_owner_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'device_data',
            },
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batv', models.CharField(max_length=50)),
                ('bat_status', models.CharField(max_length=50)),
                ('ext_sensor', models.CharField(max_length=50)),
                ('hum_sht', models.CharField(max_length=50)),
                ('tempc_ds', models.CharField(max_length=50)),
                ('tempc_sht', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
                ('current_time', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dev_eui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_data', to='api.devicedata')),
            ],
            options={
                'db_table': 'device_reading',
            },
        ),
    ]
