# Generated by Django 5.1.3 on 2024-11-11 22:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicereading',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='devicedata',
            name='dev_app_key',
            field=models.CharField(default=datetime.datetime(2024, 11, 12, 0, 23, 28, 282452), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='dev_join_eui',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='dev_eui',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='device_data', to='api.devicedata'),
        ),
    ]
