# Generated by Django 5.1.3 on 2024-11-11 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_devicereading_options_devicedata_dev_app_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereading',
            name='dev_eui',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_data', to='api.devicedata'),
        ),
    ]
