# Generated by Django 5.1.3 on 2024-11-11 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_devicereading_dev_eui'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereading',
            name='legacy_id',
            field=models.CharField(default=datetime.datetime(2024, 11, 12, 0, 38, 22, 578670), max_length=50),
            preserve_default=False,
        ),
    ]
