# Generated by Django 5.1.3 on 2024-11-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_devicereading_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='dev_nwk_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
