# Generated by Django 4.2.16 on 2024-11-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_devicedata_dev_nwk_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicereading',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='devicereading',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='devicereading',
            name='date',
        ),
        migrations.RemoveField(
            model_name='devicereading',
            name='time',
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
