# Generated by Django 5.1.3 on 2024-11-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_devicereading_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicereading",
            name="dev_eui",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="device_readings",
                to="api.devicedata",
            ),
        ),
    ]
