# Generated by Django 5.1.3 on 2024-12-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_devicereading_dev_eui"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicedata",
            name="dev_owner_email",
            field=models.CharField(max_length=200),
        ),
    ]
