# Generated by Django 5.1.3 on 2024-12-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_devicedata_dev_owner_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicedata",
            name="dev_temp_limit",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
