# Generated by Django 5.1.3 on 2025-01-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_devicedata_dev_temp_limit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devicedata",
            old_name="dev_temp_limit",
            new_name="dev_max_accepted_temp",
        ),
        migrations.AddField(
            model_name="devicedata",
            name="dev_normal_temp",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
