# Generated by Django 5.1.3 on 2025-01-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_dev_temp_limit_devicedata_dev_max_accepted_temp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicedata",
            name="dev_max_accepted_temp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="devicedata",
            name="dev_normal_temp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="devicereading",
            name="tempc_ds",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="devicereading",
            name="tempc_sht",
            field=models.FloatField(),
        ),
    ]
