# Generated by Django 5.1.6 on 2025-02-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_devicedata_dev_max_accepted_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='dev_normal_temp',
        ),
    ]
