# Generated by Django 5.1.6 on 2025-03-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_devicedata_dev_normal_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='dev_name',
            field=models.CharField(max_length=15),
        ),
    ]
