# Generated by Django 5.1.6 on 2025-05-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_devicedata_dev_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('owner_legal_id', models.CharField(max_length=20)),
            ],
        ),
    ]
