# Generated by Django 5.1.6 on 2025-05-05 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_deviceowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='dev_nwk_key',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='dev_owner_address',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='dev_owner_email',
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='dev_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_data', to='api.deviceowner'),
        ),
    ]
