# Generated by Django 5.1.6 on 2025-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_devicedata_dev_nwk_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='dev_location',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
