# Generated by Django 5.1.6 on 2025-05-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_devicedata_dev_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='dev_location',
        ),
    ]
