# Generated by Django 5.1.6 on 2025-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_devicedata_dev_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceowner',
            name='ansvsa',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
