# Generated by Django 5.1.6 on 2025-06-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_deviceowner_ansvsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='dev_nwk_key',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
