# Generated by Django 5.1.6 on 2025-06-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_devicedata_dev_nwk_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceowner',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
