# Generated by Django 5.1.6 on 2025-08-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_deviceowner_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDeviceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(choices=[('Super fresh', 'SUPER FRESH'), ('Mycell', 'MYCELL'), ('GMH', 'GMH'), ('sigmatic', 'SIGMATIC'), ('Dacica Grup', 'DACICA GRUP'), ('Kadar Gyula', 'KADAR GYULA'), ('HACCP Cluj', 'HACCP CLUJ')], default='', max_length=100)),
                ('dev_name_prefix', models.CharField(default='LGT', max_length=20)),
                ('upload_file', models.FileField(upload_to='uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='dev_app_key',
            field=models.CharField(help_text='appskey', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='dev_eui',
            field=models.CharField(help_text='deveui', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='dev_join_eui',
            field=models.CharField(help_text='appeui', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='dev_nwk_key',
            field=models.CharField(default='', help_text='nwkskey', max_length=50, null=True),
        ),
    ]
