# Generated by Django 5.1.6 on 2025-08-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_bulkdeviceupload_alter_devicedata_dev_app_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='dev_app_key',
            field=models.CharField(help_text='appkey10', max_length=50),
        ),
    ]
