# Generated by Django 5.1.6 on 2025-09-30 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_devicedata_dev_app_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='HACCPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report_data', models.JSONField(default=dict)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='api.devicedata')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
