# Generated by Django 5.1.6 on 2025-10-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_haccpreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='dev_min_accepted_temp',
            field=models.FloatField(default=-18),
        ),
    ]
