# Generated by Django 4.2.16 on 2025-10-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_devicedata_dev_min_accepted_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdeviceupload',
            name='owner',
            field=models.CharField(choices=[('Super fresh', 'SUPER FRESH'), ('Mycell', 'MYCELL'), ('GMH', 'GMH'), ('sigmatic', 'SIGMATIC'), ('Dacica Grup', 'DACICA GRUP'), ('Kadar Gyula', 'KADAR GYULA'), ('HACCP Cluj', 'HACCP CLUJ'), ('Moldovan', 'MOLDOVAN')], default='', max_length=100),
        ),
    ]
