# Generated by Django 5.1.6 on 2025-10-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_bulkdeviceupload_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdeviceupload',
            name='owner',
            field=models.CharField(choices=[('Super fresh', 'SUPER FRESH'), ('Mycell', 'MYCELL'), ('GMH', 'GMH'), ('sigmatic', 'SIGMATIC'), ('Dacica Grup', 'DACICA GRUP'), ('Kadar Gyula', 'KADAR GYULA'), ('HACCP Cluj', 'HACCP CLUJ')], default='', max_length=100),
        ),
    ]
