# Generated by Django 4.2.16 on 2026-01-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_bulkdeviceupload_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdeviceupload',
            name='owner',
            field=models.CharField(choices=[('Super fresh', 'SUPER FRESH'), ('Mycell', 'MYCELL'), ('GMH', 'GMH'), ('sigmatic', 'SIGMATIC'), ('Kadar Gyula', 'KADAR GYULA'), ('HACCP Cluj', 'HACCP CLUJ'), ('Moldovan', 'MOLDOVAN'), ('Tassid', 'TASSID')], default='', max_length=100),
        ),
    ]
