# Generated by Django 5.1.6 on 2026-02-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_bulkdeviceupload_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='dev_stop_notification_until',
            field=models.DateTimeField(default='2026-02-07 21:00'),
            preserve_default=False,
        ),
    ]
