# Generated by Django 5.1.6 on 2026-03-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_devicedata_dev_stop_notification_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='dev_name',
            field=models.CharField(max_length=50),
        ),
    ]
