# Generated by Django 5.1.6 on 2026-03-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_bulkdeviceupload_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdeviceupload',
            name='owner',
            field=models.CharField(choices=[('Super fresh', 'SUPER FRESH'), ('Mycell', 'MYCELL'), ('GMH', 'GMH'), ('sigmatic', 'SIGMATIC'), ('Kadar Gyula', 'KADAR GYULA'), ('HACCP Cluj', 'HACCP CLUJ'), ('Moldovan', 'MOLDOVAN'), ('Tassid', 'TASSID')], default='', max_length=100),
        ),
    ]
