# Generated by Django 5.1.6 on 2026-06-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_bulkdeviceupload_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='dev_cooling_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
