# Generated by Django 5.1.6 on 2026-07-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_devicedata_dev_cooling_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdeviceupload',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deviceowner'),
        ),
    ]
