# Generated by Django 4.2.16 on 2026-06-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_bulkdeviceupload_owner'),
        ('api', '0033_devicedata_dev_cooling_type'),
    ]

    operations = [
    ]
