# Generated by Django 4.2.16 on 2026-07-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_bulkdeviceupload_owner'),
        ('api', '0034_merge_20260625_2020'),
    ]

    operations = [
    ]
